AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for my CICD Pipeline PR'

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'my-cicd-${Environment}-${AWS::Region}-${AWS::AccountId}'
      Tags:
        - Key: Project
          Value: GithubActionTesting

Outputs:
  BucketName:
    Description: 'Name of the created s3 Bucket'
    Value: !Ref MyS3Bucket