AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for CICD Pipeline PR'

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'cicd-${Environment}-${AWS::Region}-${AWS::AccountId}'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  Outputs:
    BucketName:
      Description: 'Name of created s3 Bucket'
      value: !Ref MyS3Bucket